import { PERSONS } from "./data/persons.js";
import { VERBS, VERB_BY_ID } from "./data/verbs.js";
import { TENSES, TENSE_BY_ID } from "./data/tenses.js";
import { applyCompoundBlock, createExerciseItems } from "./exercise/generator.js";
import { gradeAll } from "./exercise/grader.js";
import { parseVerbInput, appendUniqueVerbIds } from "./utils/parser.js";

const app = document.querySelector("#app");
const state = {
  screen: "configuration",
  selectedVerbIds: [],
  selectedTenseIds: ["present"],
  verbOrganizationMode: "selection-order",
  tableOrientation: "persons-rows",
  colorAxis: "rows",
  colorEmphasis: "header-and-background",
  colorContrast: "subtle",
  compoundTenseMode: "select-auxiliary",
  accentChecking: "strict",
  correctionDisplayMode: "preserve-mistake",
  printContent: "answers-and-corrections",
  printWrongAnswerStyle: "strikethrough",
  exerciseData: { simpleItems: [], compoundBlocks: [] },
  unrecognized: [],
  submissionStatus: "not-submitted"
};

function escapeHtml(value) { return String(value).replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[character])); }
function checked(condition) { return condition ? " checked" : ""; }
function selected(condition) { return condition ? " selected" : ""; }
function verbName(id) { return VERB_BY_ID.get(id)?.infinitive ?? id; }
function settingSelect(label, name, options) { return `<label class="setting-control">${label}<select name="${name}" data-setting="${name}">${options.map(([value, text]) => `<option value="${value}"${selected(state[name] === value)}>${text}</option>`).join("")}</select></label>`; }
function renderSettingGrid() {
  return `<div class="settings-grid">${settingSelect("Table", "tableOrientation", [["persons-rows", "Persons → rows"], ["tenses-rows", "Tenses → rows"]])}${settingSelect("Verbs", "verbOrganizationMode", [["selection-order", "My selection/input order"], ["grouped", "Group by -ER / -IR / -RE"]])}${settingSelect("Colors", "colorEmphasis", [["header-only", "Header only"], ["header-and-background", "Header + background"]])}${settingSelect("Color follows", "colorAxis", [["rows", "Rows"], ["columns", "Columns"]])}${settingSelect("Background contrast", "colorContrast", [["subtle", "Subtle"], ["medium", "Medium"], ["high", "High"]])}${settingSelect("Compound auxiliary", "compoundTenseMode", [["select-auxiliary", "Select auxiliary"], ["manual-auxiliary", "Type auxiliary manually"]])}${settingSelect("Accent checking", "accentChecking", [["strict", "Strict"], ["ignore", "Ignore accents"]])}</div>`;
}

function renderConfiguration() {
  const selectedVerbs = new Set(state.selectedVerbIds);
  app.innerHTML = `<section class="config-page"><header class="page-heading"><p class="eyebrow">French conjugation practice</p><h1>French Verb Atelier</h1><p class="lede">Build a focused worksheet for regular and common irregular French verbs.</p></header><form id="configuration-form" class="config-layout"><section class="config-section config-verbs"><div class="section-heading"><span class="section-number">01</span><div><h2>Verbs</h2><p>Select in the order you want to practise.</p></div></div><div class="verb-picker">${[["er", "-ER"], ["ir", "-IR"], ["re", "-RE"], ["irregular", "Other"]].map(([group, label]) => `<fieldset><legend>${label}</legend>${VERBS.filter((verb) => verb.group === group).map((verb) => `<label class="check-row"><input type="checkbox" name="verb" value="${verb.id}"${checked(selectedVerbs.has(verb.id))}><span>${escapeHtml(verb.infinitive)}</span></label>`).join("")}</fieldset>`).join("")}</div><label class="field-label" for="manual-verbs">Add verbs or conjugated forms</label><textarea id="manual-verbs" rows="3" placeholder="parler, finir, avoir"></textarea><div id="unrecognized" class="notice" hidden></div><div id="selected-order" class="selected-order" aria-live="polite">${renderSelectionOrder()}</div></section><section class="config-section"><div class="section-heading"><span class="section-number">02</span><div><h2>Tenses</h2><p>Choose one or more forms.</p></div></div><div class="tense-picker">${TENSES.map((tense) => `<label class="tense-option tense-${tense.colorToken}"><input type="checkbox" name="tense" value="${tense.id}"${checked(state.selectedTenseIds.includes(tense.id))}><span><strong>${tense.displayName}</strong><small>${tense.description}</small></span></label>`).join("")}</div></section><section class="config-section settings-section"><div class="section-heading"><span class="section-number">03</span><div><h2>Worksheet settings</h2><p>Compact controls keep the worksheet focused.</p></div></div>${renderSettingGrid()}</section><div class="config-actions"><p id="config-error" class="error-text" aria-live="polite"></p><button class="primary-button" type="submit">Start practice <span aria-hidden="true">→</span></button></div></form></section>`;
  bindConfigurationEvents();
}

function renderSelectionOrder() { return state.selectedVerbIds.length ? `<span class="order-label">Order:</span> ${state.selectedVerbIds.map((id, index) => `<span class="order-chip"><b>${index + 1}</b>${escapeHtml(verbName(id))}</span>`).join("")}` : "<span class=\"muted\">No verbs selected yet.</span>"; }

function bindConfigurationEvents() {
  document.querySelectorAll('input[name="verb"]').forEach((input) => input.addEventListener("change", () => { state.selectedVerbIds = input.checked ? appendUniqueVerbIds(state.selectedVerbIds, [input.value]) : state.selectedVerbIds.filter((id) => id !== input.value); document.querySelector("#selected-order").innerHTML = renderSelectionOrder(); }));
  document.querySelector("#manual-verbs").addEventListener("blur", (event) => { const result = parseVerbInput(event.target.value); state.selectedVerbIds = appendUniqueVerbIds(state.selectedVerbIds, result.recognized); state.unrecognized = result.unrecognized; document.querySelector("#selected-order").innerHTML = renderSelectionOrder(); const notice = document.querySelector("#unrecognized"); notice.hidden = !result.unrecognized.length; notice.textContent = result.unrecognized.length ? `Unrecognized: ${result.unrecognized.join(", ")}. Correct or remove these words before starting.` : ""; document.querySelectorAll('input[name="verb"]').forEach((checkbox) => { checkbox.checked = state.selectedVerbIds.includes(checkbox.value); }); });
  document.querySelector("#configuration-form").addEventListener("change", (event) => { if (event.target.name === "tense") state.selectedTenseIds = [...document.querySelectorAll('input[name="tense"]:checked')].map((input) => input.value); if (event.target.dataset.setting) state[event.target.dataset.setting] = event.target.value; });
  document.querySelector("#configuration-form").addEventListener("submit", (event) => { event.preventDefault(); const error = document.querySelector("#config-error"); if (!state.selectedVerbIds.length) { error.textContent = "Select at least one verb."; return; } if (!state.selectedTenseIds.length) { error.textContent = "Select at least one tense."; return; } if (state.unrecognized.length) { error.textContent = "Please correct or remove unrecognized words."; return; } state.exerciseData = createExerciseItems(state.selectedVerbIds, state.selectedTenseIds); state.submissionStatus = "not-submitted"; state.screen = "practice"; renderPractice(); });
}

function getBlock(verbId, tenseId) { return state.exerciseData.compoundBlocks.find((block) => block.verbId === verbId && block.tenseId === tenseId); }
function getSimpleItem(verbId, tenseId, personId) { return state.exerciseData.simpleItems.find((item) => item.verbId === verbId && item.tenseId === tenseId && item.personId === personId); }
function colorClass(tense) { return `tense-${tense.colorToken} color-contrast-${state.colorContrast}`; }
function personColorClass(personId) { return `person-color-${personId}`; }
function renderPractice() {
  const submitted = state.submissionStatus === "submitted";
  app.dataset.printContent = state.printContent;
  const ids = state.verbOrganizationMode === "grouped" ? [...state.selectedVerbIds].sort((a, b) => VERB_BY_ID.get(a).group.localeCompare(VERB_BY_ID.get(b).group)) : state.selectedVerbIds;
  const blocks = state.verbOrganizationMode === "grouped" ? renderGroupedBlocks(ids, submitted) : ids.map((id) => renderVerbBlock(id, submitted)).join("");
  app.innerHTML = `<section class="practice-page color-emphasis-${state.colorEmphasis} color-axis-${state.colorAxis}"><header class="practice-header no-print"><div><p class="eyebrow">Practice worksheet</p><h1>Your conjugation sheet</h1></div><button class="text-button" id="edit-practice" type="button">${submitted ? "← Edit answers" : "← Edit configuration"}</button></header><section class="layout-toolbar no-print" aria-label="Practice layout controls">${settingSelect("Table", "tableOrientation", [["persons-rows", "Persons → rows"], ["tenses-rows", "Tenses → rows"]])}${settingSelect("Verbs", "verbOrganizationMode", [["selection-order", "My order"], ["grouped", "Group by type"]])}${settingSelect("Colors", "colorEmphasis", [["header-only", "Header only"], ["header-and-background", "Header + background"]])}${settingSelect("Color follows", "colorAxis", [["rows", "Rows"], ["columns", "Columns"]])}${settingSelect("Contrast", "colorContrast", [["subtle", "Subtle"], ["medium", "Medium"], ["high", "High"]])}${submitted ? settingSelect("Corrections", "correctionDisplayMode", [["preserve-mistake", "Preserve mistake"], ["replace-mistake", "Replace mistake"]]) + settingSelect("Wrong answer", "printWrongAnswerStyle", [["strikethrough", "Strikethrough"], ["red-text", "Red text"]]) : ""}</section>${submitted ? `<section class="result-summary no-print"><strong>${score().correct} / ${score().total}</strong><span>answer points correct</span></section>` : ""}<div class="worksheet">${blocks}</div>${submitted ? renderPrintSettings() : `<div class="submit-row no-print"><button class="primary-button" id="submit-practice" type="button">Submit answers <span aria-hidden="true">→</span></button></div>`}</section>`;
  bindPracticeEvents();
}
function renderGroupedBlocks(ids, submitted) { let lastGroup = ""; return ids.map((id) => { const group = VERB_BY_ID.get(id).group; const heading = group === lastGroup ? "" : `<div class="group-heading">-${group.toUpperCase()}</div>`; lastGroup = group; return heading + renderVerbBlock(id, submitted); }).join(""); }
function renderVerbBlock(verbId, submitted) { const verb = VERB_BY_ID.get(verbId); const tenses = state.selectedTenseIds.map((id) => TENSE_BY_ID.get(id)); const controls = tenses.filter((tense) => tense.type === "compound").map((tense) => renderCompoundControls(getBlock(verbId, tense.id), submitted)).join(""); return `<section class="verb-block" data-verb="${verb.id}"><div class="verb-title"><h2>${escapeHtml(verb.infinitive)}</h2><span>-${verb.group.toUpperCase()} · ${verb.defaultAuxiliary}</span></div>${controls}${state.tableOrientation === "persons-rows" ? renderPersonsRows(verbId, tenses, submitted) : renderTensesRows(verbId, tenses, submitted)}</section>`; }
function tenseHeader(tense) { return `<th class="tense-label ${colorClass(tense)}" scope="col">${tense.displayName}<small>${tense.description}</small></th>`; }
function renderPersonsRows(verbId, tenses, submitted) { return `<div class="table-scroll"><table class="conjugation-table persons-rows color-axis-${state.colorAxis}"><thead><tr><th scope="col">Person</th>${tenses.map(tenseHeader).join("")}</tr></thead><tbody>${PERSONS.map((person) => `<tr><th scope="row">${person.displayName}</th>${tenses.map((tense) => renderCell(verbId, person.id, tense, submitted)).join("")}</tr>`).join("")}</tbody></table></div>`; }
function renderTensesRows(verbId, tenses, submitted) { return `<div class="table-scroll"><table class="conjugation-table tenses-rows color-axis-${state.colorAxis}"><thead><tr><th scope="col">Tense</th>${PERSONS.map((person) => `<th class="${state.colorAxis === "columns" ? personColorClass(person.id) : ""}" scope="col">${person.displayName}</th>`).join("")}</tr></thead><tbody>${tenses.map((tense) => `<tr><th class="tense-label ${colorClass(tense)}" scope="row">${tense.displayName}</th>${PERSONS.map((person) => renderCell(verbId, person.id, tense, submitted)).join("")}</tr>`).join("")}</tbody></table></div>`; }
function renderCell(verbId, personId, tense, submitted) { const axisClass = state.colorAxis === "columns" ? personColorClass(personId) : colorClass(tense); const className = `tense-cell ${axisClass}`; if (tense.type === "compound") return `<td class="${className}">${submitted ? renderGeneratedResult(getBlock(verbId, tense.id), personId) : `<span class="generated-form">${escapeHtml(getBlock(verbId, tense.id).generatedForms[personId] || "Awaiting Apply")}</span>`}</td>`; const item = getSimpleItem(verbId, tense.id, personId); return `<td class="${className}">${submitted ? renderResult(item.grading.fullForm, item.answers.fullForm) : `<input class="answer-input" aria-label="${tense.displayName} for ${personId}" value="${escapeHtml(item.answers.fullForm)}" data-simple-item="${item.id}">`}</td>`; }
function renderCompoundControls(block, submitted) { const tense = TENSE_BY_ID.get(block.tenseId); if (submitted) { const auxiliaryCorrect = state.compoundTenseMode === "select-auxiliary" ? block.grading.auxiliary.correct : block.grading.auxiliaryCorrect; const auxiliaryText = state.compoundTenseMode === "select-auxiliary" ? block.answers.auxiliarySelection || "(blank)" : (auxiliaryCorrect ? "all auxiliary forms" : "auxiliary forms need correction"); const ppText = block.answers.pastParticiple || "(blank)"; return `<div class="compound-controls compound-result"><h3>${tense.displayName}</h3><span class="result-part">Auxiliary: ${escapeHtml(auxiliaryText)} ${auxiliaryCorrect ? "Correct" : "Incorrect"}</span><span class="result-part">Past participle: ${escapeHtml(ppText)} ${block.grading.pastParticipleCorrect ? "Correct" : "Incorrect"}</span></div>`; } const auxiliary = state.compoundTenseMode === "select-auxiliary" ? `<label>Auxiliary<select data-block="${block.id}" data-answer="auxiliarySelection"><option value="">Choose...</option><option value="avoir"${selected(block.answers.auxiliarySelection === "avoir")}>avoir</option><option value="être"${selected(block.answers.auxiliarySelection === "être")}>être</option></select></label>` : `<div class="manual-auxiliary"><span>Auxiliary</span>${PERSONS.map((person) => `<label>${person.displayName}<input value="${escapeHtml(block.answers.auxiliaryInputs[person.id])}" data-block="${block.id}" data-auxiliary-person="${person.id}"></label>`).join("")}</div>`; return `<div class="compound-controls no-print"><h3>${tense.displayName}</h3><div class="compound-control-grid">${auxiliary}<label>Past participle<input value="${escapeHtml(block.answers.pastParticiple)}" data-block="${block.id}" data-answer="pastParticiple"></label><button class="secondary-button" type="button" data-apply-block="${block.id}">Apply</button></div></div>`; }
function renderGeneratedResult(block, personId) { const expected = compoundExpected(block, personId); if (!block.grading) return block.generatedForms[personId] ? escapeHtml(block.generatedForms[personId]) : `<span class="muted">Awaiting Apply</span>`; const auxiliaryResult = state.compoundTenseMode === "select-auxiliary" ? block.grading.auxiliary : block.grading.auxiliary[personId]; const pp = block.grading.pastParticiple; if (block.grading.overallCorrect) return `<span class="correct-answer">${escapeHtml(block.generatedForms[personId])}</span>`; if (pp.correct && pp.accentDifference && auxiliaryResult.correct) return `<span class="accent-answer">${highlightAccent(expected, block.generatedForms[personId] || "")}</span>`; const style = state.printWrongAnswerStyle === "red-text" ? " wrong-red" : ""; return `<span class="wrong-answer${style}"><span class="user-correction"><s>${escapeHtml(block.generatedForms[personId] || "(blank)")}</s> → </span><strong class="correct-answer">${escapeHtml(expected)}</strong></span>`; }
function compoundExpected(block, personId) { return `${block.expected.auxiliaryForms[personId]} ${block.expected.pastParticiple}`; }
function renderResult(result, original) { if (result.correct && result.accentDifference) return `<span class="accent-answer">${highlightAccent(result.expectedAnswer, original)}</span>`; if (result.correct) return `<span class="correct-answer">${escapeHtml(result.expectedAnswer)}</span>`; if (state.correctionDisplayMode === "replace-mistake") return `<span class="correct-answer">${escapeHtml(result.expectedAnswer)}</span>`; const style = state.printWrongAnswerStyle === "red-text" ? " wrong-red" : ""; return `<span class="wrong-answer${style}"><span class="user-correction"><s>${escapeHtml(original || "(blank)")}</s> → </span><strong class="correct-answer">${escapeHtml(result.expectedAnswer)}</strong></span>`; }
function highlightAccent(expected, user) { const userCharacters = [...user]; return [...expected].map((character, index) => character === userCharacters[index] ? escapeHtml(character) : `<span class="accent-hint">${escapeHtml(character)}</span>`).join(""); }
function score() { const simple = state.exerciseData.simpleItems; const compound = state.exerciseData.compoundBlocks; const total = simple.length + compound.reduce((sum, block) => sum + 2, 0); const correct = simple.reduce((sum, item) => sum + Number(item.grading.fullForm.correct), 0) + compound.reduce((sum, block) => sum + Number(block.grading.auxiliaryCorrect) + Number(block.grading.pastParticipleCorrect), 0); return { total, correct }; }
function renderPrintSettings() { return `<section class="print-settings no-print"><h2>Print result</h2><div class="settings-grid">${settingSelect("Print content", "printContent", [["correct-only", "Correct answers only"], ["answers-and-corrections", "My answers + correct answers"]])}</div><button class="primary-button" id="print-result" type="button">Print / Save PDF <span aria-hidden="true">↗</span></button></section>`; }
function bindPracticeEvents() { document.querySelector("#edit-practice")?.addEventListener("click", () => { if (state.submissionStatus === "submitted") { state.submissionStatus = "not-submitted"; renderPractice(); } else { state.screen = "configuration"; renderConfiguration(); } }); document.querySelectorAll("[data-setting]").forEach((control) => control.addEventListener("change", () => { state[control.dataset.setting] = control.value; renderPractice(); })); document.querySelectorAll("[data-simple-item]").forEach((input) => input.addEventListener("input", () => { const item = state.exerciseData.simpleItems.find((candidate) => candidate.id === input.dataset.simpleItem); item.answers.fullForm = input.value; })); document.querySelectorAll("[data-block][data-answer]").forEach((input) => input.addEventListener("input", () => { const block = getBlockById(input.dataset.block); block.answers[input.dataset.answer] = input.value; })); document.querySelectorAll("[data-block][data-auxiliary-person]").forEach((input) => input.addEventListener("input", () => { getBlockById(input.dataset.block).answers.auxiliaryInputs[input.dataset.auxiliaryPerson] = input.value; })); document.querySelectorAll("[data-apply-block]").forEach((button) => button.addEventListener("click", () => { const block = getBlockById(button.dataset.applyBlock); state.exerciseData.compoundBlocks = state.exerciseData.compoundBlocks.map((candidate) => candidate.id === block.id ? applyCompoundBlock(candidate, state.compoundTenseMode) : candidate); renderPractice(); })); document.querySelector("#submit-practice")?.addEventListener("click", () => { state.exerciseData = gradeAll(state.exerciseData, state.accentChecking, state.compoundTenseMode); state.submissionStatus = "submitted"; renderPractice(); }); document.querySelector("#print-result")?.addEventListener("click", () => window.print()); }
function getBlockById(id) { return state.exerciseData.compoundBlocks.find((block) => block.id === id); }
renderConfiguration();
